### ISSUE TITLE
Fixed crop square moving and resizing the image below

### ISSUE THREAD

**Issue by gmogames** [lucasecf/LECropPictureViewController#11]
I would like to request a feature.

It would be good to have the option to have the crop square/circle fixed in the middle and have the user resize and move the image below to the location he wants.

I need a case where my image size should be 300x300, but users may want to put more inside the crop space then just having the image fullscreen.

Thanks!

**Comment by lucasecf** [comment]
I do see the need of this, but it would require a change so big that it would be almost a new library. And I personally don't like the experience of dragging the image inside a scroll, it was kind of the point in writing this library in the first place instead of using the default editing of the `UIImagePickerController`.

Anyways, you can achieve a similar behavior using the default's `[imagePicker setAllowsEditing:YES];`.  (although only with a square crop).

![](http://i.stack.imgur.com/IBXk9.png)

**Comment by lucasecf** [comment]
Closing this, as this was not the component purpose.
